"""initial schema

Revision ID: 45bf73c51789
Revises: 
Create Date: 2026-09-07 00:31:37.276150

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '45bf73c51789'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Enum('FEDERAL', 'STATE', name='jurisdictionlevel'), nullable=False),
    sa.Column('parent_jurisdiction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_jurisdiction_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('legal_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('JUDGE', 'PARTY', 'COURT', name='entitytype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_entities_name'), 'legal_entities', ['name'], unique=False)
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_summary', sa.Text(), nullable=False),
    sa.Column('area_of_law', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=False),
    sa.Column('courtlistener_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False, comment='0=trial, increasing toward highest appellate'),
    sa.Column('parent_court_id', sa.Integer(), nullable=True),
    sa.Column('binding_scope', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['parent_court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courts_courtlistener_id'), 'courts', ['courtlistener_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('CASE', 'STATUTE', 'REGULATION', 'SECONDARY', 'DISCOVERY', name='doctype'), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=True),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('citation_string', sa.String(length=255), nullable=True),
    sa.Column('date_decided_or_enacted', sa.Date(), nullable=True),
    sa.Column('source_type', sa.Enum('PRIMARY', 'QUASI_PRIMARY', 'SECONDARY', 'DISCOVERY', name='sourcetype'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('ingestion_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='ingestionstatus'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_citation_string'), 'documents', ['citation_string'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_table('document_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True, comment='e.g. plaintiff, defendant, author'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_entities_document_id'), 'document_entities', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_entities_entity_id'), 'document_entities', ['entity_id'], unique=False)
    op.create_table('document_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.Enum('PARAGRAPH', 'HOLDING', 'HEADNOTE', 'STATUTE_SECTION', 'FOOTNOTE', name='sectiontype'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('locator', sa.String(length=64), nullable=True, comment='e.g. page/paragraph/section no.'),
    sa.Column('embedding_ref', sa.String(length=128), nullable=True, comment='doc id in the OpenSearch index'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'sequence')
    )
    op.create_index(op.f('ix_document_sections_document_id'), 'document_sections', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_sections_embedding_ref'), 'document_sections', ['embedding_ref'], unique=False)
    op.create_table('proposition_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposition_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Enum('SUPPORT', 'OPPOSE', 'DISTINGUISH', 'LIMIT', 'REVERSE', name='propositionrelation'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['proposition_id'], ['propositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposition_documents_document_id'), 'proposition_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_proposition_documents_proposition_id'), 'proposition_documents', ['proposition_id'], unique=False)
    op.create_table('research_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sessions_user_id'), 'research_sessions', ['user_id'], unique=False)
    op.create_table('statute_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statute_document_id', sa.Integer(), nullable=False),
    sa.Column('section_no', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('effective_start', sa.Date(), nullable=True),
    sa.Column('effective_end', sa.Date(), nullable=True),
    sa.Column('amendment_of', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amendment_of'], ['statute_versions.id'], ),
    sa.ForeignKeyConstraint(['statute_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statute_versions_statute_document_id'), 'statute_versions', ['statute_document_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citing_document_id', sa.Integer(), nullable=False),
    sa.Column('citing_section_id', sa.Integer(), nullable=True),
    sa.Column('cited_document_id', sa.Integer(), nullable=True),
    sa.Column('cited_section_id', sa.Integer(), nullable=True),
    sa.Column('citation_string_raw', sa.String(length=255), nullable=False),
    sa.Column('treatment_type', sa.Enum('CITES', 'FOLLOWS', 'DISTINGUISHES', 'APPROVES', 'CRITICISES', 'OVERRULES', 'DEPARTS_FROM', 'INTERPRETS', 'APPLIES', 'NARROWS', 'EXPANDS', name='treatmenttype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extracted_by', sa.Enum('RULE', 'LLM', name='extractedby'), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cited_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['cited_section_id'], ['document_sections.id'], ),
    sa.ForeignKeyConstraint(['citing_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['citing_section_id'], ['document_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_cited_document_id'), 'citations', ['cited_document_id'], unique=False)
    op.create_index(op.f('ix_citations_citing_document_id'), 'citations', ['citing_document_id'], unique=False)
    op.create_table('research_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('modes', sa.JSON(), nullable=False),
    sa.Column('jurisdiction_filter', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_questions_session_id'), 'research_questions', ['session_id'], unique=False)
    op.create_table('research_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('structured_answer', sa.JSON(), nullable=False, comment='matches research.schemas.StructuredAnswer'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['research_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_answers_question_id'), 'research_answers', ['question_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=64), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Enum('AUTHORITY', 'INFERENCE', 'ANALOGY', 'SPECULATION', 'UNRESOLVED', name='claimtype'), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_section_id', sa.Integer(), nullable=True),
    sa.Column('extract_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['research_answers.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_section_id'], ['document_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_answer_id'), 'claims', ['answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_answer_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_research_answers_question_id'), table_name='research_answers')
    op.drop_table('research_answers')
    op.drop_index(op.f('ix_research_questions_session_id'), table_name='research_questions')
    op.drop_table('research_questions')
    op.drop_index(op.f('ix_citations_citing_document_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_cited_document_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_statute_versions_statute_document_id'), table_name='statute_versions')
    op.drop_table('statute_versions')
    op.drop_index(op.f('ix_research_sessions_user_id'), table_name='research_sessions')
    op.drop_table('research_sessions')
    op.drop_index(op.f('ix_proposition_documents_proposition_id'), table_name='proposition_documents')
    op.drop_index(op.f('ix_proposition_documents_document_id'), table_name='proposition_documents')
    op.drop_table('proposition_documents')
    op.drop_index(op.f('ix_document_sections_embedding_ref'), table_name='document_sections')
    op.drop_index(op.f('ix_document_sections_document_id'), table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index(op.f('ix_document_entities_entity_id'), table_name='document_entities')
    op.drop_index(op.f('ix_document_entities_document_id'), table_name='document_entities')
    op.drop_table('document_entities')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_documents_citation_string'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_index(op.f('ix_courts_courtlistener_id'), table_name='courts')
    op.drop_table('courts')
    op.drop_table('propositions')
    op.drop_table('orgs')
    op.drop_index(op.f('ix_legal_entities_name'), table_name='legal_entities')
    op.drop_table('legal_entities')
    op.drop_table('jurisdictions')
    # ### end Alembic commands ###
